name: proyecto_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.26.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_maps_flutter: ^2.12.2
  http: ^1.4.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  sqlite3_flutter_libs: ^0.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  drift_dev: ^2.7.0

flutter:
  uses-material-design: true
